version: "3"
services:
#  app:
#    build: .
#    links:
#      - db
#    ports:
#      - "5000:5000"
#    environment:
#      PYTHONUNBUFFERED: 1
#    networks:
#      - dbnetwork
#    depends_on:
#      - db

  localhost:
    build: db_config/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - dbnetwork
networks:
  dbnetwork: